config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  resources :fantasy_leagues do
    resources :fantasy_teams
    member do
      put :draft
    end
  end

  resources :fixtures
  resources :football_players
  resources :fantasy_team_players

end

app/models/fantasy_league.rb
class FantasyLeague < ActiveRecord::Base
  has_many :fantasy_teams
  include AASM

  aasm do
    state :forming, :initial => true
    state :drafting, :after_enter => :run_draft
    state :scheduling, :after_enter => :set_fixtures
    state :playing

    event :draft do
      transitions :from => :forming, :to => :drafting
    end

    event :schedule do
      transitions :from => :drafting, :to => :scheduling
    end

    event :play do
      transitions :from => :scheduling, :to => :playing
    end


  end

  def time_check
    gameweek = 0
    @time = Time.now
    @day = @time.a.strftime("%A")
    @hour = @time.hour
    if @day == "Sunday" and @hour == 23
      self.run_fixtures
      self.gameweek += 1
    end
  end

  def run_fixtures
  end

  def football_player_ids
    fantasy_teams.flat_map do |fantasy_team|
      fantasy_team.football_player_ids
    end
  end

  private
  def run_draft

    # goalies
    allocate_players(2, :goalkeepers)

    # defenders
    allocate_players(4, :defenders)

    # attackers
    allocate_players(4, :attackers)
    
    schedule!

    # (1..(FantasyTeam.where(fantasy_league_id: params[:id]).count)).each do |i|
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Defender").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Defender").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Defender").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Defender").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Attacker").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Attacker").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Attacker").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Attacker").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Goalkeeper").sample , fantasy_team_id: i )
    #   FantasyTeamPlayer.new(football_player_id: FootballPlayer.where(position: "Goalkeeper").sample , fantasy_team_id: i )
    # end
  end

  private
  def allocate_players(amount_of_players, position)
    amount_of_players.times do
      fantasy_teams.random.each do |fantasy_team|
        # take teams one at a time, and allocate two goalies
        fantasy_team.fantasy_team_players.create! football_player: FootballPlayer.send(position).not_in_league(self).random.first
      end
    end
  end

  # private
  # def set_fixtures
  #   index = 1
  #   fantasy_team_ids.combination(2).to_a.each do |team1, team2|
  #     Fixture.create!(home_team_id: team1, away_team_id: team2, gameweek: index)
  #     index = index + 1
  #   end
  #   fantasy_team_ids.combination(2).to_a.each do |team1, team2|
  #     Fixture.create!(home_team_id: team2, away_team_id: team1, gameweek: (index))
  #     index = index + 1
  #   end
  #   play!
  # end



  private
  def set_fixtures
    # find combinations before taking the first and 
    # last one and making them gameweek 1, then 2 and so on
    fixture = fantasy_team_ids.combination(2).to_a
    (0..((fantasy_team_ids.combination(2).count)/2)-1).each do |i|
      week = []
      week << fixture.pop
      week << fixture.shift
      week.each do |team1, team2|
        Fixture.create!(home_team_id: team1, away_team_id: team2, gameweek: i)
      end
    end
    play!
  end

end


# for each team
# sample 4 players from the defenders array and assign them to team[i]
# sample 4 players from the midfielders array and assign them to team[i]
# sample 2 players from the attackers array and assign them to team[i]
# increment i
# make sure these players are removed from the list of available players

# find the football players that are not present in fantasy team players

app/controllers/fantasy_leagues.rb
class FantasyLeaguesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_fantasy_league, only: [:show, :edit, :update, :destroy]
  
  def index
    @fantasy_leagues = FantasyLeagues.all
  end

  def new
    @fantasy_league = FantasyLeague.new
  end

  def create
    FantasyLeague.create(fantasy_league_params) 
    redirect_to(fantasy_leagues_path)
  end

  def show
  end

  def destroy
    @fantasy_league.destroy
    redirect_to(fantasy_leagues_path)
  end

  def edit
  end

  def update
    @fantasy_league.update(fantasy_league_params) 
    redirect_to(fantasy_leagues_path)
  end


  private

  def set_fantasy_league
    @fantasy_league = FantasyLeague.find(params[:id])
  end

  def fantasy_league_params
    params.require(:fantasy_league).permit(:name)
  end
end

app/controllers/fantasy_leagues_controller.rb
class FantasyLeaguesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_fantasy_league, only: [:show, :edit, :update, :destroy, :draft]
  
  def draft
    @fantasy_league.draft!
    redirect_to(@fantasy_league)
  end

  def index
    @fantasy_leagues = FantasyLeague.all
  end

  def new
    @fantasy_league = FantasyLeague.new
  end

  def create
    FantasyLeague.create(fantasy_league_params) 
    redirect_to(fantasy_leagues_path)
  end

  def show
  end

  def destroy
    @fantasy_league.destroy
    redirect_to(fantasy_leagues_path)
  end

  def edit
  end

  def update
    @fantasy_league.update(fantasy_league_params) 
    redirect_to(fantasy_leagues_path)
  end


  private

  def set_fantasy_league
    @fantasy_league = FantasyLeague.find(params[:id])
  end

  def fantasy_league_params
    params.require(:fantasy_league).permit(:name)
  end
end

app/views/fantasy_leagues/_fantasy_league.html.erb
<div class="type1"><%= fantasy_league.name %></div>
<%= button_to('Show', fantasy_league, method: :get)%>

app/views/fantasy_leagues/_form.html.erb
<%= form_for(@fantasy_league) do |f| %>
<div>
<%= f.label :name, 'Fantasy League Name:' %>
</div>
<div>
<%= f.text_field :name %>
</div>
<br>
<br>
  <center><%= f.submit "Complete" %></center>
<% end %>

app/views/fantasy_leagues/edit.html.erb
<img src="/images/hazard.jpg" class= "bg mobinvis" alt="background">
<h1>Edit Fantasy League</h1>
</div>
<%= render 'form' %>
<br>
<%= link_to 'Back', fantasy_leagues_path %>
</div>

app/views/fantasy_leagues/index.html.erb
<img src="/images/hazard.jpg" class= "bg mobinvis" alt="background">
<div class="box box-4"></div>
<div class="infoarea box box-4">
  <%= render @fantasy_leagues %>
  <br>
  <br>
    <%= link_to("New Fantasy League", new_fantasy_league_path) %>
</div>
<div class="box box-4"></div>

app/views/fantasy_leagues/new.html.erb
<img src="/images/hazard.jpg" class= "bg mobinvis" alt="background">
<h1>New Fantasy League</h1>
</div>
<%= render 'form' %>
<br>
<%= link_to 'Back', fantasy_leagues_path %>
</div>

app/views/fantasy_leagues/show.html.erb
<img src="/images/hazard.jpg" class= "bg mobinvis" alt="background">
<div class ="infoarea">
  <h2><%= @fantasy_league.name %></h2>

  <% @fantasy_league.fantasy_teams.each do |i| %>
  <div class="type1"><%= i.name %></div>
  <% end %>


<br>

<%= link_to('Add Fantasy Team', new_fantasy_league_fantasy_team_path(@fantasy_league)) %>
<%= link_to('Edit', edit_fantasy_league_path(@fantasy_league)) %>
<%= link_to('Back', fantasy_leagues_path) %>
<%= link_to('Draft', draft_fantasy_league_path(@fantasy_league), method: :put) %>
<%= link_to('Pick Team', fantasy_league_fantasy_teams_path(@fantasy_league)) %>
</div>