config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  resources :fantasy_leagues do
    resources :fantasy_teams
    member do
      put :draft
    end
  end

  resources :fixtures
  resources :football_players
  resources :fantasy_team_players

end

app/models/fantasy_team.rb
class FantasyTeam < ActiveRecord::Base
  has_many :fantasy_team_players
  has_many  :football_players, :through => :fantasy_team_players
  belongs_to :fantasy_league
  belongs_to :user
  has_many :fixtures_as_home_team, class_name: 'fixture', foreign_key: :home_team_id
  has_many :fixtures_as_away_team, class_name: 'fixture', foreign_key: :away_team_id

  scope :random, -> { order('RANDOM()') }

  include AASM
end

app/controllers/fantasy_teams.rb
class FantasyTeamsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_fantasy_team, only: [:show, :edit, :update, :destroy]
  
  def index
    @fantasy_teams = FantasyTeams.all
  end

  def new
    @fantasy_team = FantasyTeam.new
  end

  def create
    FantasyTeam.create(fantasy_team_params) 
    redirect_to(fantasy_teams_path)
  end

  def show
  end

  def destroy
    @fantasy_team.destroy
    redirect_to(fantasy_teams_path)
  end

  def edit
  end

  def update
    @fantasy_team.update(fantasy_team_params) 
    redirect_to(fantasy_teams_path)
  end


  private

  def set_fantasy_team
    @fantasy_team = FantasyTeam.find(params[:id])
  end

  def fantasy_team_params
    params.require(:fantasy_team).permit(:name, :fantasy_league_id, :user_id)
  end
end

app/controllers/fantasy_teams_controller.rb
class FantasyTeamsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_fantasy_team, only: [:show, :edit, :update, :destroy]
  before_action :set_fantasy_league
  
  def index
    @fantasy_teams = FantasyTeam.all
  end

  def new
    @fantasy_team = @fantasy_league.fantasy_teams.new
  end

  def create
    @fantasy_team = @fantasy_league.fantasy_teams.new(fantasy_team_params) 
    @fantasy_team.save!
    redirect_to(@fantasy_league)
  end

  def show
  end

  def destroy
    @fantasy_team.destroy
    redirect_to(fantasy_league_fantasy_teams_path)
  end

  def edit
  end

  def update
    @fantasy_team.update(fantasy_team_params) 
    redirect_to(fantasy_league_fantasy_teams_path)
  end


  private

  def set_fantasy_team
    @fantasy_team = FantasyTeam.find(params[:id])
  end

  def set_fantasy_league
    @fantasy_league = FantasyLeague.find(params[:fantasy_league_id])
  end

  def fantasy_team_params
    params.require(:fantasy_team).permit(:name, :user_id)
  end
end

app/views/fantasy_teams/_fantasy_team.html.erb
<div class="type1"><%= fantasy_team.name %></div>
<%= button_to('Show', fantasy_league_fantasy_team_path(fantasy_team.fantasy_league, fantasy_team), method: :get)%>

app/views/fantasy_teams/_form.html.erb
<%= form_for([@fantasy_league, @fantasy_team]) do |f| %>
<div>
<%= f.label :name, 'Fantasy Team Name:' %>
</div>
<div>
<%= f.text_field :name %>
</div>
<div>
  <%= f.label :user_id,'Manager Name' %><br>
  <%= f.select :user_id, User.all.map {|c| [c.username, c.id] } %>
</div>
<br>
<br>
  <center><%= f.submit "Complete" %></center>
<% end %>

app/views/fantasy_teams/edit.html.erb
<img src="/images/messi.jpg" class= "bg mobinvis" alt="background">
<h1>Edit Fantasy Team</h1>
</div>
<%= render 'form' %>
<br>
<%= link_to 'Back', fantasy_league_fantasy_teams_path %>
</div>

app/views/fantasy_teams/index.html.erb
<img src="/images/messi.jpg" class= "bg mobinvis" alt="background">
<%= render @fantasy_teams %>
<br>
<div>
  <%= link_to("New Fantasy Team", new_fantasy_league_fantasy_team_path) %>
</div>

app/views/fantasy_teams/new.html.erb
<img src="/images/messi.jpg" class= "bg mobinvis" alt="background">
<h1>New Fantasy Team</h1>
</div>
<%= render 'form' %>
<br>
<%= link_to 'Back', @fantasy_league %>
</div>

app/views/fantasy_teams/show.html.erb
<img src="/images/messi.jpg" class= "bg mobinvis" alt="background">

<div class="box box-12">
  <h3>Team Name: <%= @fantasy_team.name %></h3>
</div>
<div class="box box-6">
<div class="sortable" id="sortable">
    <% @fantasy_team.fantasy_team_players.each do |i| %>
    <div class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span><%= i.football_player.name %></div>
    <% end %>
    <%= link_to 'Back', fantasy_league_fantasy_teams_path %>
  </div>
</div>
<div class="box box-6">
</div>