config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  resources :fantasy_leagues do
    resources :fantasy_teams
    member do
      put :draft
    end
  end

  resources :fixtures
  resources :football_players
  resources :fantasy_team_players

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Draftplay</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>
</head>
<body>
  <div class="page-wrap">
    <div class="top box box-12">
      <% if user_signed_in? %>
      <nav class="menu">
        <ul class="moblist">
          <li class="mobsignedin">Signed in as: <%= current_user.username %></li>
          <li class="moblogout"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </nav>
      <% else %>
      <nav class="menu">
        <ul>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        </ul>
      </nav>
      <% end %>
    </div>

    <div class="mid box box-4 mobinvis">
      <!--       <img class="logo-img img-circle" src="http://i.imgur.com/YQVhwzl.png"> -->
    </div>

    <div class="mid box box-4 mobinvis">

      <!--     <img class="logo2-img" src="http://www.fantasyfootballgeek.co.uk/wp-content/uploads/2014/12/giroud.png"> -->

    </div>

    <div class="mid box box-4 mobinvis">

    </div>

    <ul class="navbar">
          <li class="nav"><%= link_to "Leagues", fantasy_leagues_path %></li>
          <li class="nav"><%= link_to "Transfers", fantasy_team_players_path %></li>
          <li class="nav"><%= link_to "Fixtures", fixtures_path %></li>
          <li class="nav"><%= link_to "Help", "https://upload.wikimedia.org/wikipedia/commons/4/4c/Tangerine_2009-03-11.jpg" %></li>
    </ul>


    <%= yield %>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <footer class="site-footer">
  </footer>
</body>
</html>